// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpESTX7yNTm96wvH4Wg8U-_52MUUmKSgw',
    appId: '1:118771867481:web:c19f605a95e1a840e7f648',
    messagingSenderId: '118771867481',
    projectId: 'electron-iq-cross',
    authDomain: 'electron-iq-cross.firebaseapp.com',
    storageBucket: 'electron-iq-cross.firebasestorage.app',
    measurementId: 'G-8PJYD8M0B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL_66ZKxE-Dy_M4_BNZLw4R0x0Km08QtQ',
    appId: '1:118771867481:android:9d8252f3e53000fee7f648',
    messagingSenderId: '118771867481',
    projectId: 'electron-iq-cross',
    storageBucket: 'electron-iq-cross.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkAlEjZ7J_yhdRafXCQ-d6dcZHmHX-50',
    appId: '1:118771867481:ios:a637f3b2d3f4c048e7f648',
    messagingSenderId: '118771867481',
    projectId: 'electron-iq-cross',
    storageBucket: 'electron-iq-cross.firebasestorage.app',
    androidClientId: '118771867481-9aocka78c66svi560ak8i0v4dpn034gr.apps.googleusercontent.com',
    iosClientId: '118771867481-8u2kc4sslndqu81vqkusn35s9rpscrm9.apps.googleusercontent.com',
    iosBundleId: 'com.sham.ElectronIQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRkAlEjZ7J_yhdRafXCQ-d6dcZHmHX-50',
    appId: '1:118771867481:ios:e2f1f5660c00cf82e7f648',
    messagingSenderId: '118771867481',
    projectId: 'electron-iq-cross',
    storageBucket: 'electron-iq-cross.firebasestorage.app',
    androidClientId: '118771867481-9aocka78c66svi560ak8i0v4dpn034gr.apps.googleusercontent.com',
    iosClientId: '118771867481-ai684bhn9h9un7kbrr25kl6tdcf7knqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronIq',
  );

}