// lib/Datas/periodic_table_data.dart

import 'package:flutter/material.dart' show Color;

enum ElementCategory {
  alkaliMetal,
  alkalineEarthMetal,
  lanthanide,
  actinide,
  transitionMetal,
  postTransitionMetal,
  metalloid,
  polyatomicNonmetal,
  diatomicNonmetal,
  nobleGas,
  unknown
}

class ChemicalElement {
  final String name;
  final String symbol;
  final int atomicNumber;
  final double atomicMass;
  final ElementCategory category;
  final int group;
  final int period;
  final String summary;
  final List<int> electronConfiguration;
  final String? meltingPoint;
  final String? density;
  final String block;
  final String? imagePath;
  final String? imageTitle; // <-- Added property

  const ChemicalElement({
    required this.name,
    required this.symbol,
    required this.atomicNumber,
    required this.atomicMass,
    required this.category,
    required this.group,
    required this.period,
    required this.summary,
    required this.electronConfiguration,
    this.meltingPoint,
    this.density,
    required this.block,
    this.imagePath,
    this.imageTitle, // <-- Added to constructor
  });
}

const Map<ElementCategory, Color> categoryColors = {
  ElementCategory.alkaliMetal: Color(0xFFE57373), // Soft Red
  ElementCategory.alkalineEarthMetal: Color(0xFFFFB74D), // Warm Amber
  ElementCategory.lanthanide: Color(0xFFF48FB1), // Soft Pink
  ElementCategory.actinide: Color(0xFFBA68C8), // Violet
  ElementCategory.transitionMetal: Color(0xFF64B5F6), // Soft Blue
  ElementCategory.postTransitionMetal: Color(0xFF90A4AE), // Cool Grey-Blue
  ElementCategory.metalloid: Color(0xFF4DB6AC), // Teal
  ElementCategory.polyatomicNonmetal: Color(0xFF81C784), // Soft Green
  ElementCategory.diatomicNonmetal: Color(0xFFA5D6A7), // Light Mint
  ElementCategory.nobleGas: Color(0xFF4FC3F7), // Sky Blue
  ElementCategory.unknown: Color(0xFFB0BEC5), // Neutral Grey
};


const List<ChemicalElement> periodicTableElements = [
    ChemicalElement(name: 'Hydrogen', symbol: 'H', atomicNumber: 1, atomicMass: 1.008, category: ElementCategory.diatomicNonmetal, group: 1, period: 1, summary: 'A colorless, odorless, flammable gas that is the simplest and most abundant element in the universe.', electronConfiguration: [1], meltingPoint: "-259.14°C", density: "0.0899 g/cm³", block: 's-block', imagePath: 'assets/elementImages/h_hydrogen.jpg', imageTitle: 'Spectrum of gaseous hydrogen'),
    ChemicalElement(name: 'Helium', symbol: 'He', atomicNumber: 2, atomicMass: 4.0026, category: ElementCategory.nobleGas, group: 18, period: 1, summary: 'A colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table.', electronConfiguration: [2], meltingPoint: "-272.2°C", density: "0.1785 g/cm³", block: 's-block', imagePath: 'assets/elementImages/he_helium.jpg', imageTitle: 'Spectrum of gaseous helium'),
    ChemicalElement(name: 'Lithium', symbol: 'Li', atomicNumber: 3, atomicMass: 6.94, category: ElementCategory.alkaliMetal, group: 1, period: 2, summary: 'A soft, silvery-white alkali metal. Under standard conditions, it is the lightest metal and the least dense solid element.', electronConfiguration: [2, 1], meltingPoint: "180.54°C", density: "0.534 g/cm³", block: 's-block', imagePath: 'assets/elementImages/li_lithium.jpg', imageTitle: 'Lithium sublimed dendrites'),
    ChemicalElement(name: 'Beryllium', symbol: 'Be', atomicNumber: 4, atomicMass: 9.0122, category: ElementCategory.alkalineEarthMetal, group: 2, period: 2, summary: 'A relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.', electronConfiguration: [2, 2], meltingPoint: "1278°C", density: "1.848 g/cm³", block: 's-block', imagePath: 'assets/elementImages/be_beryllium.jpg', imageTitle: 'Beryllium sublimed dendrites'),
    ChemicalElement(name: 'Boron', symbol: 'B', atomicNumber: 5, atomicMass: 10.81, category: ElementCategory.metalloid, group: 13, period: 2, summary: 'A low-abundance element in the Solar System and in the Earth\'s crust. It is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals.', electronConfiguration: [2, 3], meltingPoint: "2076°C", density: "2.34 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/b_boron.jpg', imageTitle: 'Pure Crystalline Boron'),
    ChemicalElement(name: 'Carbon', symbol: 'C', atomicNumber: 6, atomicMass: 12.011, category: ElementCategory.polyatomicNonmetal, group: 14, period: 2, summary: 'A nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table.', electronConfiguration: [2, 4], meltingPoint: "3550°C", density: "2.267 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/c_carbon.jpg', imageTitle: 'Amorphous Carbon'),
    ChemicalElement(name: 'Nitrogen', symbol: 'N', atomicNumber: 7, atomicMass: 14.007, category: ElementCategory.diatomicNonmetal, group: 15, period: 2, summary: 'The most common element in the Earth\'s atmosphere, and a primary constituent of all living matter.', electronConfiguration: [2, 5], meltingPoint: "-209.86°C", density: "1.251 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/n_nitrogen.jpg', imageTitle: 'Liquid Nitrogen'),
    ChemicalElement(name: 'Oxygen', symbol: 'O', atomicNumber: 8, atomicMass: 15.999, category: ElementCategory.diatomicNonmetal, group: 16, period: 2, summary: 'A member of the chalcogen group on the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.', electronConfiguration: [2, 6], meltingPoint: "-218.79°C", density: "1.429 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/o_oxygen.jpg', imageTitle: 'Liquid Oxygen'),
    ChemicalElement(name: 'Fluorine', symbol: 'F', atomicNumber: 9, atomicMass: 18.998, category: ElementCategory.diatomicNonmetal, group: 17, period: 2, summary: 'The lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.', electronConfiguration: [2, 7], meltingPoint: "-219.67°C", density: "1.696 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/f_fluorine.jpg', imageTitle: 'Liquid Fluorine'),
    ChemicalElement(name: 'Neon', symbol: 'Ne', atomicNumber: 10, atomicMass: 20.180, category: ElementCategory.nobleGas, group: 18, period: 2, summary: 'A colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air.', electronConfiguration: [2, 8], meltingPoint: "-248.59°C", density: "0.9 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/ne_neon.jpg', imageTitle: 'Spectrum of gaseous neon'),
    ChemicalElement(name: 'Sodium', symbol: 'Na', atomicNumber: 11, atomicMass: 22.990, category: ElementCategory.alkaliMetal, group: 1, period: 3, summary: 'A soft, silvery-white, highly reactive metal.', electronConfiguration: [2, 8, 1], meltingPoint: "97.72°C", density: "0.968 g/cm³", block: 's-block', imagePath: 'assets/elementImages/na_sodium.jpg', imageTitle: 'Sodium metal'),
    ChemicalElement(name: 'Magnesium', symbol: 'Mg', atomicNumber: 12, atomicMass: 24.305, category: ElementCategory.alkalineEarthMetal, group: 2, period: 3, summary: 'An alkaline earth metal and the eighth-most-abundant element in the Earth\'s crust.', electronConfiguration: [2, 8, 2], meltingPoint: "650°C", density: "1.738 g/cm³", block: 's-block', imagePath: 'assets/elementImages/mg_magnesium.jpg', imageTitle: 'Magnesium ribbon'),
    ChemicalElement(name: 'Aluminum', symbol: 'Al', atomicNumber: 13, atomicMass: 26.982, category: ElementCategory.postTransitionMetal, group: 13, period: 3, summary: 'A silvery-white, soft, non-magnetic and ductile metal in the boron group.', electronConfiguration: [2, 8, 3], meltingPoint: "660.32°C", density: "2.7 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/al_aluminum.jpg', imageTitle: 'Aluminum foil'),
    ChemicalElement(name: 'Silicon', symbol: 'Si', atomicNumber: 14, atomicMass: 28.085, category: ElementCategory.metalloid, group: 14, period: 3, summary: 'A hard, brittle crystalline solid with a blue-grey metallic lustre, and is a tetravalent metalloid and semiconductor.', electronConfiguration: [2, 8, 4], meltingPoint: "1414°C", density: "2.329 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/si_silicon.jpg', imageTitle: 'Polycrystalline Silicon'),
    ChemicalElement(name: 'Phosphorus', symbol: 'P', atomicNumber: 15, atomicMass: 30.974, category: ElementCategory.polyatomicNonmetal, group: 15, period: 3, summary: 'A multivalent nonmetal of the nitrogen group, phosphorus as a mineral is almost always present in its maximally oxidized state, as inorganic phosphate rocks.', electronConfiguration: [2, 8, 5], meltingPoint: "44.1°C", density: "1.82 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/p_phosphorus.jpg', imageTitle: 'White Phosphorus'),
    ChemicalElement(name: 'Sulfur', symbol: 'S', atomicNumber: 16, atomicMass: 32.06, category: ElementCategory.polyatomicNonmetal, group: 16, period: 3, summary: 'An abundant, multivalent and non-metallic element. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S8.', electronConfiguration: [2, 8, 6], meltingPoint: "112.8°C", density: "2.07 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/s_sulfur.jpg', imageTitle: 'Sulfur crystals'),
    ChemicalElement(name: 'Chlorine', symbol: 'Cl', atomicNumber: 17, atomicMass: 35.45, category: ElementCategory.diatomicNonmetal, group: 17, period: 3, summary: 'The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.', electronConfiguration: [2, 8, 7], meltingPoint: "-101.5°C", density: "3.214 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/cl_chlorine.jpg', imageTitle: 'Liquid Chlorine'),
    ChemicalElement(name: 'Argon', symbol: 'Ar', atomicNumber: 18, atomicMass: 39.948, category: ElementCategory.nobleGas, group: 18, period: 3, summary: 'The third-most abundant gas in the Earth\'s atmosphere, at 0.934% (9340 ppmv). It is more than twice as abundant as water vapor.', electronConfiguration: [2, 8, 8], meltingPoint: "-189.35°C", density: "1.784 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/ar_argon.jpg', imageTitle: 'Spectrum of gaseous argon'),
    ChemicalElement(name: 'Potassium', symbol: 'K', atomicNumber: 19, atomicMass: 39.098, category: ElementCategory.alkaliMetal, group: 1, period: 4, summary: 'A silvery-white metal that is soft enough to be cut with a knife with little force.', electronConfiguration: [2, 8, 8, 1], meltingPoint: "63.38°C", density: "0.862 g/cm³", block: 's-block', imagePath: 'assets/elementImages/k_potassium.jpg', imageTitle: 'Potassium metal'),
    ChemicalElement(name: 'Calcium', symbol: 'Ca', atomicNumber: 20, atomicMass: 40.078, category: ElementCategory.alkalineEarthMetal, group: 2, period: 4, summary: 'The fifth most abundant element in Earth\'s crust, and the third most abundant metal, after iron and aluminium.', electronConfiguration: [2, 8, 8, 2], meltingPoint: "839°C", density: "1.55 g/cm³", block: 's-block', imagePath: 'assets/elementImages/ca_calcium.jpg', imageTitle: 'Calcium crystals'),
    ChemicalElement(name: 'Scandium', symbol: 'Sc', atomicNumber: 21, atomicMass: 44.956, category: ElementCategory.transitionMetal, group: 3, period: 4, summary: 'A silvery-white metallic d-block element, it has historically been sometimes classified as a rare-earth element, together with yttrium and the lanthanides.', electronConfiguration: [2, 8, 9, 2], meltingPoint: "1541°C", density: "2.989 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/sc_scandium.jpg', imageTitle: 'Scandium sublimed dendrites'),
    ChemicalElement(name: 'Titanium', symbol: 'Ti', atomicNumber: 22, atomicMass: 47.867, category: ElementCategory.transitionMetal, group: 4, period: 4, summary: 'A lustrous transition metal with a silver color, low density, and high strength. Titanium is resistant to corrosion in sea water, aqua regia, and chlorine.', electronConfiguration: [2, 8, 10, 2], meltingPoint: "1668°C", density: "4.506 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/ti_titanium.jpg', imageTitle: 'Titanium crystal bar'),
    ChemicalElement(name: 'Vanadium', symbol: 'V', atomicNumber: 23, atomicMass: 50.942, category: ElementCategory.transitionMetal, group: 5, period: 4, summary: 'A hard, silvery-grey, ductile, malleable transition metal. The elemental metal is rarely found in nature, but once isolated artificially, the formation of an oxide layer stabilizes the free metal somewhat against further oxidation.', electronConfiguration: [2, 8, 11, 2], meltingPoint: "1910°C", density: "6.11 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/v_vanadium.jpg', imageTitle: 'Vanadium crystal'),
    ChemicalElement(name: 'Chromium', symbol: 'Cr', atomicNumber: 24, atomicMass: 51.996, category: ElementCategory.transitionMetal, group: 6, period: 4, summary: 'A steely-grey, lustrous, hard and brittle metal which takes a high polish, resists tarnishing, and has a high melting point.', electronConfiguration: [2, 8, 13, 1], meltingPoint: "1907°C", density: "7.19 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/cr_chromium.jpg', imageTitle: 'Electrolytic Chromium'),
    ChemicalElement(name: 'Manganese', symbol: 'Mn', atomicNumber: 25, atomicMass: 54.938, category: ElementCategory.transitionMetal, group: 7, period: 4, summary: 'Not found as a free element in nature; it is often found in minerals in combination with iron. Manganese is a transition metal with a multifaceted array of industrial alloy uses, particularly in stainless steels.', electronConfiguration: [2, 8, 13, 2], meltingPoint: "1246°C", density: "7.44 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/mn_manganese.jpg', imageTitle: 'Electrolytic Manganese'),
    ChemicalElement(name: 'Iron', symbol: 'Fe', atomicNumber: 26, atomicMass: 55.845, category: ElementCategory.transitionMetal, group: 8, period: 4, summary: 'A metal that belongs to the first transition series and group 8 of the periodic table. It is by mass the most common element on Earth, forming much of Earth\'s outer and inner core.', electronConfiguration: [2, 8, 14, 2], meltingPoint: "1538°C", density: "7.874 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/fe_iron.jpg', imageTitle: 'Iron electrolitic'),
    ChemicalElement(name: 'Cobalt', symbol: 'Co', atomicNumber: 27, atomicMass: 58.933, category: ElementCategory.transitionMetal, group: 9, period: 4, summary: 'A hard, lustrous, silver-grey metal.', electronConfiguration: [2, 8, 15, 2], meltingPoint: "1495°C", density: "8.9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/co_cobalt.jpg', imageTitle: 'Cobalt electrolitic'),
    ChemicalElement(name: 'Nickel', symbol: 'Ni', atomicNumber: 28, atomicMass: 58.693, category: ElementCategory.transitionMetal, group: 10, period: 4, summary: 'A silvery-white lustrous metal with a slight golden tinge. Nickel belongs to the transition metals and is hard and ductile.', electronConfiguration: [2, 8, 16, 2], meltingPoint: "1455°C", density: "8.908 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/ni_nickel.jpg', imageTitle: 'Nickel pellets'),
    ChemicalElement(name: 'Copper', symbol: 'Cu', atomicNumber: 29, atomicMass: 63.546, category: ElementCategory.transitionMetal, group: 11, period: 4, summary: 'A soft, malleable, and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a reddish-orange color.', electronConfiguration: [2, 8, 18, 1], meltingPoint: "1084.62°C", density: "8.96 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/cu_copper.jpg', imageTitle: 'Copper crystal'),
    ChemicalElement(name: 'Zinc', symbol: 'Zn', atomicNumber: 30, atomicMass: 65.38, category: ElementCategory.transitionMetal, group: 12, period: 4, summary: 'The first element in group 12 of the periodic table. In some respects zinc is chemically similar to magnesium.', electronConfiguration: [2, 8, 18, 2], meltingPoint: "419.53°C", density: "7.14 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/zn_zinc.jpg', imageTitle: 'Zinc crystal'),
    ChemicalElement(name: 'Gallium', symbol: 'Ga', atomicNumber: 31, atomicMass: 69.723, category: ElementCategory.postTransitionMetal, group: 13, period: 4, summary: 'A soft, silvery metal, and elemental gallium is a brittle solid at low temperatures, and melts at 29.76 °C (85.57 °F) (slightly above room temperature).', electronConfiguration: [2, 8, 18, 3], meltingPoint: "29.76°C", density: "5.907 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/ga_gallium.jpg', imageTitle: 'Gallium crystal'),
    ChemicalElement(name: 'Germanium', symbol: 'Ge', atomicNumber: 32, atomicMass: 72.630, category: ElementCategory.metalloid, group: 14, period: 4, summary: 'A lustrous, hard-brittle, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon.', electronConfiguration: [2, 8, 18, 4], meltingPoint: "937.4°C", density: "5.323 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/ge_germanium.jpg', imageTitle: 'Polycrystalline Germanium'),
    ChemicalElement(name: 'Arsenic', symbol: 'As', atomicNumber: 33, atomicMass: 74.922, category: ElementCategory.metalloid, group: 15, period: 4, summary: 'Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal. Arsenic is a metalloid.', electronConfiguration: [2, 8, 18, 5], meltingPoint: "817°C", density: "5.727 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/as_arsenic.jpg', imageTitle: 'Metallic Arsenic'),
    ChemicalElement(name: 'Selenium', symbol: 'Se', atomicNumber: 34, atomicMass: 78.971, category: ElementCategory.polyatomicNonmetal, group: 16, period: 4, summary: 'A nonmetal with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic.', electronConfiguration: [2, 8, 18, 6], meltingPoint: "221°C", density: "4.809 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/se_selenium.jpg', imageTitle: 'Selenium crystals'),
    ChemicalElement(name: 'Bromine', symbol: 'Br', atomicNumber: 35, atomicMass: 79.904, category: ElementCategory.diatomicNonmetal, group: 17, period: 4, summary: 'The third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas. Its properties are thus intermediate between those of chlorine and iodine.', electronConfiguration: [2, 8, 18, 7], meltingPoint: "-7.2°C", density: "3.12 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/br_bromine.jpg', imageTitle: 'Liquid Bromine'),
    ChemicalElement(name: 'Krypton', symbol: 'Kr', atomicNumber: 36, atomicMass: 83.798, category: ElementCategory.nobleGas, group: 18, period: 4, summary: 'A colorless, odorless, tasteless noble gas that occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps.', electronConfiguration: [2, 8, 18, 8], meltingPoint: "-157.2°C", density: "3.708 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/kr_krypton.jpg', imageTitle: 'Spectrum of gaseous krypton'),
    ChemicalElement(name: 'Rubidium', symbol: 'Rb', atomicNumber: 37, atomicMass: 85.468, category: ElementCategory.alkaliMetal, group: 1, period: 5, summary: 'A very soft, silvery-white metal in the alkali metal group. Rubidium metal is similar to potassium metal and cesium metal in physical appearance, softness and conductivity.', electronConfiguration: [2, 8, 18, 8, 1], meltingPoint: "39.31°C", density: "1.532 g/cm³", block: 's-block', imagePath: 'assets/elementImages/rb_rubidium.jpg', imageTitle: 'Rubidium metal'),
    ChemicalElement(name: 'Strontium', symbol: 'Sr', atomicNumber: 38, atomicMass: 87.62, category: ElementCategory.alkalineEarthMetal, group: 2, period: 5, summary: 'An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically. The metal forms a dark oxide layer when it is exposed to air.', electronConfiguration: [2, 8, 18, 8, 2], meltingPoint: "777°C", density: "2.64 g/cm³", block: 's-block', imagePath: 'assets/elementImages/sr_strontium.jpg', imageTitle: 'Strontium crystal'),
    ChemicalElement(name: 'Yttrium', symbol: 'Y', atomicNumber: 39, atomicMass: 88.906, category: ElementCategory.transitionMetal, group: 3, period: 5, summary: 'A silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a "rare-earth element".', electronConfiguration: [2, 8, 18, 9, 2], meltingPoint: "1522°C", density: "4.472 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/y_yttrium.jpg', imageTitle: 'Yttrium sublimed dendrites'),
    ChemicalElement(name: 'Zirconium', symbol: 'Zr', atomicNumber: 40, atomicMass: 91.224, category: ElementCategory.transitionMetal, group: 4, period: 5, summary: 'A lustrous, greyish-white, soft, ductile, malleable metal that is solid at room temperature, though it is hard and brittle at lesser purities.', electronConfiguration: [2, 8, 18, 10, 2], meltingPoint: "1855°C", density: "6.506 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/zr_zirconium.jpg', imageTitle: 'Zirconium crystal bar'),
    ChemicalElement(name: 'Niobium', symbol: 'Nb', atomicNumber: 41, atomicMass: 92.906, category: ElementCategory.transitionMetal, group: 5, period: 5, summary: 'A light grey, crystalline, and ductile transition metal. Pure niobium is quite soft and ductile, but impurities make it harder.', electronConfiguration: [2, 8, 18, 12, 1], meltingPoint: "2477°C", density: "8.57 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/nb_niobium.jpg', imageTitle: 'Niobium crystal'),
    ChemicalElement(name: 'Molybdenum', symbol: 'Mo', atomicNumber: 42, atomicMass: 95.96, category: ElementCategory.transitionMetal, group: 6, period: 5, summary: 'A silvery-white metal with a gray cast and is chemically related to chromium and tungsten. It readily forms hard, stable carbides in alloys.', electronConfiguration: [2, 8, 18, 13, 1], meltingPoint: "2623°C", density: "10.28 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/mo_molybdenum.jpg', imageTitle: 'Molybdenum crystal'),
    ChemicalElement(name: 'Technetium', symbol: 'Tc', atomicNumber: 43, atomicMass: 98, category: ElementCategory.transitionMetal, group: 7, period: 5, summary: 'The lightest element whose isotopes are all radioactive; none are stable.', electronConfiguration: [2, 8, 18, 13, 2], meltingPoint: "2157°C", density: "11.5 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/tc_technetium.jpg', imageTitle: 'Technetium metal'),
    ChemicalElement(name: 'Ruthenium', symbol: 'Ru', atomicNumber: 44, atomicMass: 101.07, category: ElementCategory.transitionMetal, group: 8, period: 5, summary: 'A rare transition metal belonging to the platinum group of the periodic table. It is generally found as a minor component of platinum ores.', electronConfiguration: [2, 8, 18, 15, 1], meltingPoint: "2334°C", density: "12.37 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/ru_ruthenium.jpg', imageTitle: 'Ruthenium crystal'),
    ChemicalElement(name: 'Rhodium', symbol: 'Rh', atomicNumber: 45, atomicMass: 102.91, category: ElementCategory.transitionMetal, group: 9, period: 5, summary: 'A rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal. It is a noble metal and a member of the platinum group.', electronConfiguration: [2, 8, 18, 16, 1], meltingPoint: "1964°C", density: "12.41 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/rh_rhodium.jpg', imageTitle: 'Rhodium ring'),
    ChemicalElement(name: 'Palladium', symbol: 'Pd', atomicNumber: 46, atomicMass: 106.42, category: ElementCategory.transitionMetal, group: 10, period: 5, summary: 'A rare and lustrous silvery-white metal. It is a noble metal and a member of the platinum group.', electronConfiguration: [2, 8, 18, 18], meltingPoint: "1554.9°C", density: "12.02 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/pd_palladium.jpg', imageTitle: 'Palladium leaf'),
    ChemicalElement(name: 'Silver', symbol: 'Ag', atomicNumber: 47, atomicMass: 107.87, category: ElementCategory.transitionMetal, group: 11, period: 5, summary: 'A soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.', electronConfiguration: [2, 8, 18, 18, 1], meltingPoint: "961.78°C", density: "10.49 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/ag_silver.jpg', imageTitle: 'Silver crystal'),
    ChemicalElement(name: 'Cadmium', symbol: 'Cd', atomicNumber: 48, atomicMass: 112.41, category: ElementCategory.transitionMetal, group: 12, period: 5, summary: 'A soft, silvery-white metal which is chemically similar to the two other stable metals in group 12, zinc and mercury.', electronConfiguration: [2, 8, 18, 18, 2], meltingPoint: "320.9°C", density: "8.65 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/cd_cadmium.jpg', imageTitle: 'Cadmium crystal'),
    ChemicalElement(name: 'Indium', symbol: 'In', atomicNumber: 49, atomicMass: 114.82, category: ElementCategory.postTransitionMetal, group: 13, period: 5, summary: 'The softest metal that is not an alkali metal. It is a silvery-white metal that looks like tin.', electronConfiguration: [2, 8, 18, 18, 3], meltingPoint: "156.6°C", density: "7.31 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/in_indium.jpg', imageTitle: 'Indium metal'),
    ChemicalElement(name: 'Tin', symbol: 'Sn', atomicNumber: 50, atomicMass: 118.71, category: ElementCategory.postTransitionMetal, group: 14, period: 5, summary: 'A silvery metal that characteristically has a faint yellow hue. Tin, like indium, is soft enough to be cut without much force.', electronConfiguration: [2, 8, 18, 18, 4], meltingPoint: "231.93°C", density: "7.31 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/sn_tin.jpg', imageTitle: 'Tin cry'),
    ChemicalElement(name: 'Antimony', symbol: 'Sb', atomicNumber: 51, atomicMass: 121.76, category: ElementCategory.metalloid, group: 15, period: 5, summary: 'A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite.', electronConfiguration: [2, 8, 18, 18, 5], meltingPoint: "630.63°C", density: "6.697 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/sb_antimony.jpg', imageTitle: 'Antimony crystal'),
    ChemicalElement(name: 'Tellurium', symbol: 'Te', atomicNumber: 52, atomicMass: 127.60, category: ElementCategory.metalloid, group: 16, period: 5, summary: 'A brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur.', electronConfiguration: [2, 8, 18, 18, 6], meltingPoint: "449.51°C", density: "6.24 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/te_tellurium.jpg', imageTitle: 'Tellurium crystal'),
    ChemicalElement(name: 'Iodine', symbol: 'I', atomicNumber: 53, atomicMass: 126.90, category: ElementCategory.diatomicNonmetal, group: 17, period: 5, summary: 'A heavy, non-metallic element, that is solid at room temperature and has a shiny, purplish-black appearance.', electronConfiguration: [2, 8, 18, 18, 7], meltingPoint: "113.7°C", density: "4.94 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/i_iodine.jpg', imageTitle: 'Iodine crystals'),
    ChemicalElement(name: 'Xenon', symbol: 'Xe', atomicNumber: 54, atomicMass: 131.29, category: ElementCategory.nobleGas, group: 18, period: 5, summary: 'A heavy, colorless, odorless noble gas, Xenon is found in the Earth\'s atmosphere in trace amounts.', electronConfiguration: [2, 8, 18, 18, 8], meltingPoint: "-111.8°C", density: "5.895 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/xe_xenon.jpg', imageTitle: 'Solid Xenon'),
    ChemicalElement(name: 'Cesium', symbol: 'Cs', atomicNumber: 55, atomicMass: 132.91, category: ElementCategory.alkaliMetal, group: 1, period: 6, summary: 'A soft, silvery-gold alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.', electronConfiguration: [2, 8, 18, 18, 8, 1], meltingPoint: "28.44°C", density: "1.873 g/cm³", block: 's-block', imagePath: 'assets/elementImages/cs_cesium.jpg', imageTitle: 'Cesium metal'),
    ChemicalElement(name: 'Barium', symbol: 'Ba', atomicNumber: 56, atomicMass: 137.33, category: ElementCategory.alkalineEarthMetal, group: 2, period: 6, summary: 'The fifth element in group 2 and is a soft, silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element.', electronConfiguration: [2, 8, 18, 18, 8, 2], meltingPoint: "727°C", density: "3.51 g/cm³", block: 's-block', imagePath: 'assets/elementImages/ba_barium.jpg', imageTitle: 'Barium metal'),
    ChemicalElement(name: 'Lanthanum', symbol: 'La', atomicNumber: 57, atomicMass: 138.91, category: ElementCategory.lanthanide, group: 3, period: 6, summary: 'A soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air and is soft enough to be cut with a knife.', electronConfiguration: [2, 8, 18, 18, 9, 2], meltingPoint: "920°C", density: "6.146 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/la_lanthanum.jpg', imageTitle: 'Lanthanum metal'),
    ChemicalElement(name: 'Cerium', symbol: 'Ce', atomicNumber: 58, atomicMass: 140.12, category: ElementCategory.lanthanide, group: 4, period: 6, summary: 'A soft, ductile, and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a steel kitchen knife.', electronConfiguration: [2, 8, 18, 19, 9, 2], meltingPoint: "798°C", density: "6.77 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/ce_cerium.jpg', imageTitle: 'Cerium metal'),
    ChemicalElement(name: 'Praseodymium', symbol: 'Pr', atomicNumber: 59, atomicMass: 140.91, category: ElementCategory.lanthanide, group: 5, period: 6, summary: 'The third member of the lanthanide series and is considered to be one of the rare-earth metals.', electronConfiguration: [2, 8, 18, 21, 8, 2], meltingPoint: "931°C", density: "6.773 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/pr_praseodymium.jpg', imageTitle: 'Praseodymium metal'),
    ChemicalElement(name: 'Neodymium', symbol: 'Nd', atomicNumber: 60, atomicMass: 144.24, category: ElementCategory.lanthanide, group: 6, period: 6, summary: 'A soft silvery metal that tarnishes in air. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach.', electronConfiguration: [2, 8, 18, 22, 8, 2], meltingPoint: "1021°C", density: "7.007 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/nd_neodymium.jpg', imageTitle: 'Neodymium metal'),
    ChemicalElement(name: 'Promethium', symbol: 'Pm', atomicNumber: 61, atomicMass: 145, category: ElementCategory.lanthanide, group: 7, period: 6, summary: 'A chemical element with the symbol Pm and atomic number 61. All of its isotopes are radioactive.', electronConfiguration: [2, 8, 18, 23, 8, 2], meltingPoint: "1045°C", density: "7.26 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/pm_promethium.jpg', imageTitle: 'Promethium metal'),
    ChemicalElement(name: 'Samarium', symbol: 'Sm', atomicNumber: 62, atomicMass: 150.36, category: ElementCategory.lanthanide, group: 8, period: 6, summary: 'A moderately hard silvery metal that slowly oxidizes in air.', electronConfiguration: [2, 8, 18, 24, 8, 2], meltingPoint: "1072°C", density: "7.52 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/sm_samarium.jpg', imageTitle: 'Samarium sublimed dendrites'),
    ChemicalElement(name: 'Europium', symbol: 'Eu', atomicNumber: 63, atomicMass: 151.96, category: ElementCategory.lanthanide, group: 9, period: 6, summary: 'The most reactive of the lanthanide elements by far. It has to be stored under an inert fluid to protect it from atmospheric oxygen or moisture.', electronConfiguration: [2, 8, 18, 25, 8, 2], meltingPoint: "822°C", density: "5.244 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/eu_europium.jpg', imageTitle: 'Europium sublimed dendrites'),
    ChemicalElement(name: 'Gadolinium', symbol: 'Gd', atomicNumber: 64, atomicMass: 157.25, category: ElementCategory.lanthanide, group: 10, period: 6, summary: 'A silvery-white, malleable, and ductile rare-earth element. It is found in nature only in oxidized form.', electronConfiguration: [2, 8, 18, 25, 9, 2], meltingPoint: "1313°C", density: "7.9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/gd_gadolinium.jpg', imageTitle: 'Gadolinium sublimed dendrites'),
    ChemicalElement(name: 'Terbium', symbol: 'Tb', atomicNumber: 65, atomicMass: 158.93, category: ElementCategory.lanthanide, group: 11, period: 6, summary: 'A silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife.', electronConfiguration: [2, 8, 18, 27, 8, 2], meltingPoint: "1356°C", density: "8.23 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/tb_terbium.jpg', imageTitle: 'Terbium sublimed dendrites'),
    ChemicalElement(name: 'Dysprosium', symbol: 'Dy', atomicNumber: 66, atomicMass: 162.50, category: ElementCategory.lanthanide, group: 12, period: 6, summary: 'A rare earth element that has a metallic, bright silver luster. It is a member of the lanthanide series.', electronConfiguration: [2, 8, 18, 28, 8, 2], meltingPoint: "1412°C", density: "8.55 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/dy_dysprosium.jpg', imageTitle: 'Dysprosium sublimed dendrites'),
    ChemicalElement(name: 'Holmium', symbol: 'Ho', atomicNumber: 67, atomicMass: 164.93, category: ElementCategory.lanthanide, group: 13, period: 6, summary: 'A rare-earth element, holmium is a bright, soft, silvery-white, corrosion-resistant, and malleable metal.', electronConfiguration: [2, 8, 18, 29, 8, 2], meltingPoint: "1474°C", density: "8.8 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/ho_holmium.jpg', imageTitle: 'Holmium sublimed dendrites'),
    ChemicalElement(name: 'Erbium', symbol: 'Er', atomicNumber: 68, atomicMass: 167.26, category: ElementCategory.lanthanide, group: 14, period: 6, summary: 'A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements.', electronConfiguration: [2, 8, 18, 30, 8, 2], meltingPoint: "1529°C", density: "9.066 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/er_erbium.jpg', imageTitle: 'Erbium sublimed dendrites'),
    ChemicalElement(name: 'Thulium', symbol: 'Tm', atomicNumber: 69, atomicMass: 168.93, category: ElementCategory.lanthanide, group: 15, period: 6, summary: 'The second-least abundant of the lanthanides, after promethium. It is an easily workable metal with a bright silvery-gray luster.', electronConfiguration: [2, 8, 18, 31, 8, 2], meltingPoint: "1545°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/tm_thulium.jpg', imageTitle: 'Thulium sublimed dendrites'),
    ChemicalElement(name: 'Ytterbium', symbol: 'Yb', atomicNumber: 70, atomicMass: 173.05, category: ElementCategory.lanthanide, group: 16, period: 6, summary: 'A soft, malleable and rather ductile element that exhibits a bright silvery luster.', electronConfiguration: [2, 8, 18, 32, 8, 2], meltingPoint: "824°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/yb_ytterbium.jpg', imageTitle: 'Ytterbium sublimed dendrites'),
    ChemicalElement(name: 'Lutetium', symbol: 'Lu', atomicNumber: 71, atomicMass: 174.97, category: ElementCategory.lanthanide, group: 17, period: 6, summary: 'A silvery white metal, which resists corrosion in dry air, but not in moist air.', electronConfiguration: [2, 8, 18, 32, 9, 2], meltingPoint: "1652°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/lu_lutetium.jpg', imageTitle: 'Lutetium sublimed dendrites'),
    ChemicalElement(name: 'Hafnium', symbol: 'Hf', atomicNumber: 72, atomicMass: 178.49, category: ElementCategory.transitionMetal, group: 4, period: 6, summary: 'A lustrous, silvery-gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.', electronConfiguration: [2, 8, 18, 32, 10, 2], meltingPoint: "2233°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/hf_hafnium.jpg', imageTitle: 'Hafnium crystal bar'),
    ChemicalElement(name: 'Tantalum', symbol: 'Ta', atomicNumber: 73, atomicMass: 180.95, category: ElementCategory.transitionMetal, group: 5, period: 6, summary: 'A rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.', electronConfiguration: [2, 8, 18, 32, 11, 2], meltingPoint: "3017°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/ta_tantalum.jpg', imageTitle: 'Tantalum crystal'),
    ChemicalElement(name: 'Tungsten', symbol: 'W', atomicNumber: 74, atomicMass: 183.84, category: ElementCategory.transitionMetal, group: 6, period: 6, summary: 'A rare metal found naturally on Earth almost exclusively combined with other elements in chemical compounds rather than alone.', electronConfiguration: [2, 8, 18, 32, 12, 2], meltingPoint: "3422°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/w_tungsten.jpg', imageTitle: 'Tungsten crystal'),
    ChemicalElement(name: 'Rhenium', symbol: 'Re', atomicNumber: 75, atomicMass: 186.21, category: ElementCategory.transitionMetal, group: 7, period: 6, summary: 'A silvery-white, heavy, third-row transition metal in group 7 of the periodic table.', electronConfiguration: [2, 8, 18, 32, 13, 2], meltingPoint: "3186°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/re_rhenium.jpg', imageTitle: 'Rhenium crystal'),
    ChemicalElement(name: 'Osmium', symbol: 'Os', atomicNumber: 76, atomicMass: 190.23, category: ElementCategory.transitionMetal, group: 8, period: 6, summary: 'A hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.', electronConfiguration: [2, 8, 18, 32, 14, 2], meltingPoint: "3033°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/os_osmium.jpg', imageTitle: 'Osmium crystal'),
    ChemicalElement(name: 'Iridium', symbol: 'Ir', atomicNumber: 77, atomicMass: 192.22, category: ElementCategory.transitionMetal, group: 9, period: 6, summary: 'A very hard, brittle, silvery-white transition metal of the platinum group, iridium is considered to be the second-densest element (after osmium).', electronConfiguration: [2, 8, 18, 32, 15, 2], meltingPoint: "2446°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/ir_iridium.jpg', imageTitle: 'Iridium crystal'),
    ChemicalElement(name: 'Platinum', symbol: 'Pt', atomicNumber: 78, atomicMass: 195.08, category: ElementCategory.transitionMetal, group: 10, period: 6, summary: 'A dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal.', electronConfiguration: [2, 8, 18, 32, 17, 1], meltingPoint: "1768.3°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/pt_platinum.jpg', imageTitle: 'Platinum nugget'),
    ChemicalElement(name: 'Gold', symbol: 'Au', atomicNumber: 79, atomicMass: 196.97, category: ElementCategory.transitionMetal, group: 11, period: 6, summary: 'A bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.', electronConfiguration: [2, 8, 18, 32, 18, 1], meltingPoint: "1064.18°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/au_gold.jpg', imageTitle: 'Gold nugget'),
    ChemicalElement(name: 'Mercury', symbol: 'Hg', atomicNumber: 80, atomicMass: 200.59, category: ElementCategory.transitionMetal, group: 12, period: 6, summary: 'Commonly known as quicksilver and was formerly named hydrargyrum. A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure.', electronConfiguration: [2, 8, 18, 32, 18, 2], meltingPoint: "-38.83°C", density: "9 g/cm³", block: 'd-block', imagePath: 'assets/elementImages/hg_mercury.jpg', imageTitle: 'Mercury drop'),
    ChemicalElement(name: 'Thallium', symbol: 'Tl', atomicNumber: 81, atomicMass: 204.38, category: ElementCategory.postTransitionMetal, group: 13, period: 6, summary: 'A grey post-transition metal that is not found free in nature. When isolated, thallium resembles tin, but discolors when exposed to air.', electronConfiguration: [2, 8, 18, 32, 18, 3], meltingPoint: "303.5°C", density: "9 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/tl_thallium.jpg', imageTitle: 'Thallium metal'),
    ChemicalElement(name: 'Lead', symbol: 'Pb', atomicNumber: 82, atomicMass: 207.2, category: ElementCategory.postTransitionMetal, group: 14, period: 6, summary: 'A heavy metal that is denser than most common materials. Lead is soft and malleable, and has a relatively low melting point.', electronConfiguration: [2, 8, 18, 32, 18, 4], meltingPoint: "327.46°C", density: "9 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/pb_lead.jpg', imageTitle: 'Lead metal'),
    ChemicalElement(name: 'Bismuth', symbol: 'Bi', atomicNumber: 83, atomicMass: 208.98, category: ElementCategory.postTransitionMetal, group: 15, period: 6, summary: 'A brittle metal with a silvery-white color when freshly produced, but surface oxidation can give it a pink tinge. Bismuth is the most naturally diamagnetic element and has one of the lowest values of thermal conductivity among metals.', electronConfiguration: [2, 8, 18, 32, 18, 5], meltingPoint: "271.3°C", density: "9 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/bi_bismuth.jpg', imageTitle: 'Bismuth crystal'),
    ChemicalElement(name: 'Polonium', symbol: 'Po', atomicNumber: 84, atomicMass: 209, category: ElementCategory.postTransitionMetal, group: 16, period: 6, summary: 'A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to bismuth and tellurium, and it occurs in uranium ores.', electronConfiguration: [2, 8, 18, 32, 18, 6], meltingPoint: "254°C", density: "9 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/po_polonium.jpg', imageTitle: 'Polonium metal'),
    ChemicalElement(name: 'Astatine', symbol: 'At', atomicNumber: 85, atomicMass: 210, category: ElementCategory.metalloid, group: 17, period: 6, summary: 'The rarest naturally occurring element in the Earth\'s crust, it is a radioactive element that is produced by the decay of heavier elements.', electronConfiguration: [2, 8, 18, 32, 18, 7], meltingPoint: "302°C", density: "9 g/cm³", block: 'p-block', imagePath: null, imageTitle: 'Astatine (no image available)'),
    ChemicalElement(name: 'Radon', symbol: 'Rn', atomicNumber: 86, atomicMass: 222, category: ElementCategory.nobleGas, group: 18, period: 6, summary: 'A radioactive, colorless, odorless, tasteless noble gas. It is one of the densest substances that remains a gas under normal conditions.', electronConfiguration: [2, 8, 18, 32, 18, 8], meltingPoint: "-71°C", density: "9 g/cm³", block: 'p-block', imagePath: 'assets/elementImages/rn_radon.jpg', imageTitle: 'Spectrum of gaseous radon'),
    ChemicalElement(name: 'Francium', symbol: 'Fr', atomicNumber: 87, atomicMass: 223, category: ElementCategory.alkaliMetal, group: 1, period: 7, summary: 'The second most electropositive element, behind only caesium, and is the second rarest naturally occurring element (after astatine).', electronConfiguration: [2, 8, 18, 32, 18, 8, 1], meltingPoint: "27°C", density: "9 g/cm³", block: 's-block', imagePath: null, imageTitle: 'Francium (no image available)'),
    ChemicalElement(name: 'Radium', symbol: 'Ra', atomicNumber: 88, atomicMass: 226, category: ElementCategory.alkalineEarthMetal, group: 2, period: 7, summary: 'Almost pure-white, but it readily oxidizes on exposure to air, turning from silvery-white to black.', electronConfiguration: [2, 8, 18, 32, 18, 8, 2], meltingPoint: "700°C", density: "9 g/cm³", block: 's-block', imagePath: 'assets/elementImages/ra_radium.jpg', imageTitle: 'Radium metal'),
    ChemicalElement(name: 'Actinium', symbol: 'Ac', atomicNumber: 89, atomicMass: 227, category: ElementCategory.actinide, group: 3, period: 7, summary: 'A soft, silvery-white, radioactive metal. In the periodic table, it is located in group 3 and period 7.', electronConfiguration: [2, 8, 18, 32, 18, 9, 2], meltingPoint: "1050°C", density: "9 g/cm³", block: 'f-block', imagePath: null, imageTitle: 'Actinium (no image available)'),
    ChemicalElement(name: 'Thorium', symbol: 'Th', atomicNumber: 90, atomicMass: 232.04, category: ElementCategory.actinide, group: 4, period: 7, summary: 'A weakly radioactive metallic chemical element with symbol Th and atomic number 90. Thorium is silvery and tarnishes black when it is exposed to air, forming thorium dioxide; it is moderately hard, malleable, and has a high melting point.', electronConfiguration: [2, 8, 18, 32, 18, 10, 2], meltingPoint: "1750°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/th_thorium.jpg', imageTitle: 'Thorium metal'),
    ChemicalElement(name: 'Protactinium', symbol: 'Pa', atomicNumber: 91, atomicMass: 231.04, category: ElementCategory.actinide, group: 5, period: 7, summary: 'A dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.', electronConfiguration: [2, 8, 18, 32, 20, 9, 2], meltingPoint: "1572°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/pa_protactinium.jpg', imageTitle: 'Protactinium metal'),
    ChemicalElement(name: 'Uranium', symbol: 'U', atomicNumber: 92, atomicMass: 238.03, category: ElementCategory.actinide, group: 6, period: 7, summary: 'A silvery-white metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.', electronConfiguration: [2, 8, 18, 32, 21, 9, 2], meltingPoint: "1132.3°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/u_uranium.jpg', imageTitle: 'Uranium metal'),
    ChemicalElement(name: 'Neptunium', symbol: 'Np', atomicNumber: 93, atomicMass: 237, category: ElementCategory.actinide, group: 7, period: 7, summary: 'A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus.', electronConfiguration: [2, 8, 18, 32, 22, 9, 2], meltingPoint: "637°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/np_neptunium.jpg', imageTitle: 'Neptunium metal'),
    ChemicalElement(name: 'Plutonium', symbol: 'Pu', atomicNumber: 94, atomicMass: 244, category: ElementCategory.actinide, group: 8, period: 7, summary: 'An actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.', electronConfiguration: [2, 8, 18, 32, 24, 8, 2], meltingPoint: "639.5°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/pu_plutonium.jpg', imageTitle: 'Plutonium ring'),
    ChemicalElement(name: 'Americium', symbol: 'Am', atomicNumber: 95, atomicMass: 243, category: ElementCategory.actinide, group: 9, period: 7, summary: 'A synthetic element that is silvery-white and radioactive. It is a transuranic member of the actinide series.', electronConfiguration: [2, 8, 18, 32, 25, 8, 2], meltingPoint: "994°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/am_americium.jpg', imageTitle: 'Americium metal'),
    ChemicalElement(name: 'Curium', symbol: 'Cm', atomicNumber: 96, atomicMass: 247, category: ElementCategory.actinide, group: 10, period: 7, summary: 'A transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity.', electronConfiguration: [2, 8, 18, 32, 25, 9, 2], meltingPoint: "1340°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/cm_curium.jpg', imageTitle: 'Curium metal'),
    ChemicalElement(name: 'Berkelium', symbol: 'Bk', atomicNumber: 97, atomicMass: 247, category: ElementCategory.actinide, group: 11, period: 7, summary: 'A transuranic radioactive chemical element with the symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series.', electronConfiguration: [2, 8, 18, 32, 27, 8, 2], meltingPoint: "986°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/bk_berkelium.jpg', imageTitle: 'Berkelium metal'),
    ChemicalElement(name: 'Californium', symbol: 'Cf', atomicNumber: 98, atomicMass: 251, category: ElementCategory.actinide, group: 12, period: 7, summary: 'A radioactive metallic chemical element with symbol Cf and atomic number 98. The element was first made in 1950 at the University of California Radiation Laboratory in Berkeley.', electronConfiguration: [2, 8, 18, 32, 28, 8, 2], meltingPoint: "900°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/cf_californium.jpg', imageTitle: 'Californium metal'),
    ChemicalElement(name: 'Einsteinium', symbol: 'Es', atomicNumber: 99, atomicMass: 252, category: ElementCategory.actinide, group: 13, period: 7, summary: 'A synthetic element with the symbol Es and atomic number 99. As a member of the actinide series, it is the seventh transuranic element.', electronConfiguration: [2, 8, 18, 32, 29, 8, 2], meltingPoint: "860°C", density: "9 g/cm³", block: 'f-block', imagePath: 'assets/elementImages/es_einsteinium.jpg', imageTitle: 'Einsteinium metal'),
    ChemicalElement(name: 'Fermium', symbol: 'Fm', atomicNumber: 100, atomicMass: 257, category: ElementCategory.actinide, group: 14, period: 7, summary: 'A synthetic element with the symbol Fm and atomic number 100. It is the heaviest element that can be formed by neutron bombardment of lighter elements.', electronConfiguration: [2, 8, 18, 32, 30, 8, 2], meltingPoint: "1527°C", density: "9 g/cm³", block: 'f-block', imagePath: null, imageTitle: 'Fermium (no image available)'),
    ChemicalElement(name: 'Mendelevium', symbol: 'Md', atomicNumber: 101, atomicMass: 258, category: ElementCategory.actinide, group: 15, period: 7, summary: 'A synthetic element with chemical symbol Md (formerly Mv) and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that was not synthesized by neutron irradiation of lighter elements.', electronConfiguration: [2, 8, 18, 32, 31, 8, 2], meltingPoint: "827°C", density: "9 g/cm³", block: 'f-block', imagePath: null, imageTitle: 'Mendelevium (no image available)'),
    ChemicalElement(name: 'Nobelium', symbol: 'No', atomicNumber: 102, atomicMass: 259, category: ElementCategory.actinide, group: 16, period: 7, summary: 'A synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science.', electronConfiguration: [2, 8, 18, 32, 32, 8, 2], meltingPoint: "827°C", density: "9 g/cm³", block: 'f-block', imagePath: null, imageTitle: 'Nobelium (no image available)'),
    ChemicalElement(name: 'Lawrencium', symbol: 'Lr', atomicNumber: 103, atomicMass: 262, category: ElementCategory.actinide, group: 17, period: 7, summary: 'A synthetic chemical element with chemical symbol Lr (formerly Lw) and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements.', electronConfiguration: [2, 8, 18, 32, 32, 8, 3], meltingPoint: "1900°C", density: "9 g/cm³", block: 'f-block', imagePath: null, imageTitle: 'Lawrencium (no image available)'),
    ChemicalElement(name: 'Rutherfordium', symbol: 'Rf', atomicNumber: 104, atomicMass: 267, category: ElementCategory.transitionMetal, group: 4, period: 7, summary: 'A synthetic chemical element, it is a superheavy element and is radioactive.', electronConfiguration: [2, 8, 18, 32, 32, 10, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Rutherfordium (no image available)'),
    ChemicalElement(name: 'Dubnium', symbol: 'Db', atomicNumber: 105, atomicMass: 268, category: ElementCategory.transitionMetal, group: 5, period: 7, summary: 'A synthetic chemical element. Dubnium is highly radioactive: the most stable known isotope, dubnium-268, has a half-life of about 28 hours.', electronConfiguration: [2, 8, 18, 32, 32, 11, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Dubnium (no image available)'),
    ChemicalElement(name: 'Seaborgium', symbol: 'Sg', atomicNumber: 106, atomicMass: 269, category: ElementCategory.transitionMetal, group: 6, period: 7, summary: 'A synthetic chemical element, it is a radioactive element that was first synthesized in 1974.', electronConfiguration: [2, 8, 18, 32, 32, 12, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Seaborgium (no image available)'),
    ChemicalElement(name: 'Bohrium', symbol: 'Bh', atomicNumber: 107, atomicMass: 270, category: ElementCategory.transitionMetal, group: 7, period: 7, summary: 'A synthetic chemical element. It is named after Danish physicist Niels Bohr. As a synthetic element, it can be created in a laboratory but is not found in nature.', electronConfiguration: [2, 8, 18, 32, 32, 13, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Bohrium (no image available)'),
    ChemicalElement(name: 'Hassium', symbol: 'Hs', atomicNumber: 108, atomicMass: 277, category: ElementCategory.transitionMetal, group: 8, period: 7, summary: 'A synthetic chemical element, named after the German state of Hesse. It is a radioactive element that does not exist in nature and is created in a laboratory.', electronConfiguration: [2, 8, 18, 32, 32, 14, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Hassium (no image available)'),
    ChemicalElement(name: 'Meitnerium', symbol: 'Mt', atomicNumber: 109, atomicMass: 278, category: ElementCategory.unknown, group: 9, period: 7, summary: 'A synthetic chemical element. It is an extremely radioactive synthetic element (an element not found in nature, but can be created in a laboratory).', electronConfiguration: [2, 8, 18, 32, 32, 15, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Meitnerium (no image available)'),
    ChemicalElement(name: 'Darmstadtium', symbol: 'Ds', atomicNumber: 110, atomicMass: 281, category: ElementCategory.unknown, group: 10, period: 7, summary: 'A synthetic chemical element. It is an extremely radioactive synthetic element.', electronConfiguration: [2, 8, 18, 32, 32, 17, 1], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Darmstadtium (no image available)'),
    ChemicalElement(name: 'Roentgenium', symbol: 'Rg', atomicNumber: 111, atomicMass: 282, category: ElementCategory.unknown, group: 11, period: 7, summary: 'A synthetic chemical element. It is an extremely radioactive synthetic element and can only be created in a laboratory.', electronConfiguration: [2, 8, 18, 32, 32, 18, 1], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Roentgenium (no image available)'),
    ChemicalElement(name: 'Copernicium', symbol: 'Cn', atomicNumber: 112, atomicMass: 285, category: ElementCategory.transitionMetal, group: 12, period: 7, summary: 'A synthetic chemical element. It is an extremely radioactive synthetic element that can only be created in a laboratory.', electronConfiguration: [2, 8, 18, 32, 32, 18, 2], meltingPoint: null, density: null, block: 'd-block', imagePath: null, imageTitle: 'Copernicium (no image available)'),
    ChemicalElement(name: 'Nihonium', symbol: 'Nh', atomicNumber: 113, atomicMass: 286, category: ElementCategory.unknown, group: 13, period: 7, summary: 'A synthetic chemical element. It is a superheavy element and is extremely radioactive.', electronConfiguration: [2, 8, 18, 32, 32, 18, 3], meltingPoint: null, density: null, block: 'p-block', imagePath: null, imageTitle: 'Nihonium (no image available)'),
    ChemicalElement(name: 'Flerovium', symbol: 'Fl', atomicNumber: 114, atomicMass: 289, category: ElementCategory.postTransitionMetal, group: 14, period: 7, summary: 'A superheavy artificial chemical element. It is an extremely radioactive synthetic element.', electronConfiguration: [2, 8, 18, 32, 32, 18, 4], meltingPoint: null, density: null, block: 'p-block', imagePath: null, imageTitle: 'Flerovium (no image available)'),
    ChemicalElement(name: 'Moscovium', symbol: 'Mc', atomicNumber: 115, atomicMass: 290, category: ElementCategory.unknown, group: 15, period: 7, summary: 'A synthetic chemical element. It is an extremely radioactive element; its most stable known isotope, moscovium-290, has a half-life of just 0.8 seconds.', electronConfiguration: [2, 8, 18, 32, 32, 18, 5], meltingPoint: null, density: null, block: 'p-block', imagePath: null, imageTitle: 'Moscovium (no image available)'),
    ChemicalElement(name: 'Livermorium', symbol: 'Lv', atomicNumber: 116, atomicMass: 293, category: ElementCategory.unknown, group: 16, period: 7, summary: 'A synthetic superheavy element. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature.', electronConfiguration: [2, 8, 18, 32, 32, 18, 6], meltingPoint: null, density: null, block: 'p-block', imagePath: null, imageTitle: 'Livermorium (no image available)'),
    ChemicalElement(name: 'Tennessine', symbol: 'Ts', atomicNumber: 117, atomicMass: 294, category: ElementCategory.unknown, group: 17, period: 7, summary: 'A synthetic superheavy element. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.', electronConfiguration: [2, 8, 18, 32, 32, 18, 7], meltingPoint: null, density: null, block: 'p-block', imagePath: null, imageTitle: 'Tennessine (no image available)'),
    ChemicalElement(name: 'Oganesson', symbol: 'Og', atomicNumber: 118, atomicMass: 294, category: ElementCategory.unknown, group: 18, period: 7, summary: 'A synthetic chemical element. It has the highest atomic number and highest atomic mass of all known elements.', electronConfiguration: [2, 8, 18, 32, 32, 18, 8], meltingPoint: null, density: null, block: 'p-block', imagePath: null, imageTitle: 'Oganesson (no image available)'),
];

